var App = angular.module('footballApp', []);

App.controller('positionController', function($scope, $http) {

  //starting sum for the projected of each team

  $scope.sumOne = 0;
  $scope.sumTwo = 0;

  //JSON data for both teams
  //skip to line 240 for the rest of the code 

  //change player projected scores to see team totals change
  //and the win/lose in action
  $scope.teamone = [
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3139477.png",
        "name": "Patrick Mahomes",
        "depthchart": "Starter",
        "team": "Kansas City Chiefs",
        "projected": 27.4,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FFB81C",
        "tmColorDark": "#C9243F",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
        "headlineNews": "Lights up Baltimore",
        "report": "Mahomes completed 27 of 37 passes for 374 yards and three touchdowns during Sunday's 33-28 win over the Ravens. He fumbled once in the contest, but it was recovered.",
        "analysis": "Mahomes enjoyed another terrific second quarter Sunday, dropping off a 18-yard touchdown to Demarcus Robinson and then following up with an 83-yard seed to Mecole Hardman. Mahomes had topped 1,000 yards passing for the season by halftime and is on pace for a jaw-dropping 6,373 yards to go along with 53 scores for the season, with no signs of letting up. Next up is a hot Lions team that has tempered talented passers Phillip Rivers and Carson Wentz in back-to-back weeks."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/14881.png",
        "name": "Russell Wilson",
        "depthchart": "Starter",
        "team": "Seattle Seahawks",
        "projected": 26.6,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#69BE28",
        "tmColorDark": "#002244",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
        "headlineNews": "Piles up four total scores",
        "report": "Wilson completed 32 of 50 passes for 406 yards and two touchdowns in Sunday's 33-27 loss to the Saints. He also ran seven times for 51 yards and two scores.",
        "analysis": "It was a monster game for Wilson, who was on the run often but avoided a sack for the first time this season. Just as important, this game revealed that coach Pete Carroll was willing to abandon the run-heavy motto if the Seahawks trailed by enough, as Wilson's 50 pass attempts were the most of his career. It also helped that starting running back Chris Carson's fumble woes resurfaced. Nevertheless, Wilson took over this game and will have a good shot to do the same thing in Week 4 versus the Cardinals, who just allowed Kyle Allen to throw for 261 yards and four scores in his second career start."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/5529.png",
        "name": "Philip Rivers",
        "depthchart": "Starter",
        "team": "Los Angeles Chargers",
        "projected": 25.8,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#0080C6",
        "tmColorDark": "#002A5E",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
        "headlineNews": "Tops 300 yards",
        "report": "Rivers completed 31 of his 46 pass attempts for 318 yards and two touchdowns in Week 3 against the Texans. He also added two rushes for nine yards.",
        "analysis": "Rivers was routinely pressured and sacked five times, making it difficult for him to operate efficiently. That said, his gaudy yardage total was based mostly on volume as he averaged only 6.9 yards per attempt. Regardless of how it's come, Rivers has been especially productive through three games this season, racking up 944 passing yards and five touchdowns. He'll look to keep things going in a positive Week 4 matchup against the Dolphins."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3916387.png",
        "name": "Lamar Jackson",
        "depthchart": "Starter",
        "team": "Baltimore Ravens",
        "projected": 24.0,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#9E7C0C",
        "tmColorDark": "#241773",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
        "headlineNews": "Cools a bit in Kansas City",
        "report": "Jackson completed 22 of 43 passes for 267 yards and added 46 yards and a touchdown on eight carries during Sunday's 33-28 loss to the Chiefs.",
        "analysis": "An impressive, cork-screwing run in the game's final moments salvaged what was an otherwise so-so day for Jackson. The Chiefs jumped out to a big early lead, forcing Jackson to operate more from the pocket. Though he avoided disaster, the low completion percentage and bizarre cross-field throw to Willie Snead that was somehow pulled down by the veteran wideout are certain to be topics of conversation in the coming week. Jackson will face his biggest test of the young season Sunday against division-rival Cleveland."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3918298.png",
        "name": "Josh Allen",
        "depthchart": "Starter",
        "team": "Buffalo Bills",
        "projected": 21.3,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#C60C30",
        "tmColorDark": "#00338D",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
        "headlineNews": "Finally contained as rusher",
        "report": "Allen completed 23 of 36 passes for 243 yards, a touchdown, a two-point conversion and an interception in Sunday's 21-17 win over the Bengals. He rushed nine times for 46 yards and fumbled twice, but the ball was recovered by the offense both times.",
        "analysis": "Allen opened the scoring with a one-yard touchdown to tight end Dawson Knox and added a two-point conversion to Cole Beasley. He also let the Bengals back into the game, as his third-quarter interception was returned to the 22-yard line, and Buffalo's 14-0 lead was cut in half three plays later. Turnovers continue to be a bugaboo for the second-year quarterback, and he's still a below-average passer who has never thrown for more than 254 yards in a game, but this was the first time this season that he failed to record a rushing touchdown. Allen has guided the Bills to a 3-0 record against a trio of lackluster teams, but the competition gets a lot stiffer in Week 4, when the undefeated Patriots come to town."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3116407.png",
        "name": "Mason Rudolph",
        "depthchart": "Starter",
        "team": "Pittsburgh Steelers",
        "projected": 20.8,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FFB612",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
        "headlineNews": "Erratic in first start",
        "report": "Rudolph completed 14 of 27 passes for 174 yards and two touchdowns with one interception in Sunday's 24-20 loss to the 49ers.",
        "analysis": "He also ran the ball four times for 15 yards. Rudolph appeared trapped in a caretaker role for most of the first half as coach Mike Tomlin tried to get by on the team's running game, but once the Steelers fell behind in the second half, the second-year QB started taking some shots downfield and was rewarded with long TD tosses to JuJu Smith-Schuster and Diontae Johnson. With the jitters of his first NFL start behind him, Rudolph will look to post better numbers in Week 4 against a Bengals defense that's had trouble slowing anyone down to date."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/11237.png",
        "name": "Matt Ryan",
        "depthchart": "Starter",
        "team": "Atlanta Falcons",
        "projected": 20.6,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#A71930",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
        "headlineNews": "Two straight three-TD outings",
        "report": "Ryan completed 29 of 34 pass attempts for 304 yards, with three touchdowns and one interception during Sunday's 27-24 loss to Indianapolis.",
        "analysis": "With a stellar statistical outing Sunday against Indianapolis, the 2016 MVP now has 300-plus passing yards and multiple passing touchdowns in three straight games to kick off the season. The bugaboo to this point, however, has been an abundance of giveaways, as Ryan has already committed six interceptions in 2019 after throwing seven all of last year. In Week 4 Ryan will face a capable opponent as he aims to get his team back to .500, taking on a Titans defense that has already forced four interceptions, and is holding offenses to 212 passing yards per game."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3917315.png",
        "name": "Kyler Murray",
        "depthchart": "Starter",
        "team": "Arizona Cardinals",
        "projected": 19.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#97233F",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
        "headlineNews": "Flashes mobility in loss",
        "report": "Murray completed 30 of 43 passes for 173 yards and two touchdowns with two interceptions, while gaining 69 rushing yards on eight carries, in Sunday's 38-20 loss to the Panthers.",
        "analysis": "Some of the scrambles were by design, but Murray also spent a good portion of the game running for his life from the Carolina pass russ: He was sacked eight times, and the lack of time he had to let routes develop accounted for his miserable 4.0 YPA. Murray is showing the tools to be a top fantasy QB, but until the Arizona offensive line can give him better protection, his production is likely to remain erratic."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/16757.png",
        "name": "Derek Carr",
        "depthchart": "Starter",
        "team": "Oakland Raiders",
        "projected": 19.0,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#A5ACAF",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/oak.png",
        "headlineNews": "Sacked four times by Vikings",
        "report": "Carr completed 27 of 34 pass attempts for 242 yards with two touchdowns and one interception during Sunday's 34-14 road loss to the Vikings.",
        "analysis": "The 28-year-old eclipsed 240 passing yards in Week 3 against Minnesota after being held under the 200-yard mark and throwing two interceptions last week against the Chiefs. What's also encouraging for Carr is the fact that he threw multiple passing touchdowns for the first time since Week 14 of last season, despite facing a Vikings secondary that sports two former All-Pros in Harrison Smith and Xavier Rhodes. Up next is a matchup against an Indianapolis defense that gave up three passing touchdowns and north of 300 yards to Falcons quarterback Matt Ryan in Week 3."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3122840.png",
        "name": "Deshaun Watson",
        "depthchart": "Starter",
        "team": "Houston Texans",
        "projected": 18.9,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#A71930",
        "tmColorDark": "#03202F",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
        "headlineNews": "Another big day",
        "report": "Watson completed 24 of his 34 pass attempts for 351 yards and three touchdowns in Week 3 against the Chargers. He also rushed the ball seven times for 18 yards.",
        "analysis": "Watson passed for three touchdowns for the second time in three contests this season. However he displayed improved efficiency,  as he completed a season-best 73 percent of his passes and also averaged over 10 yards per attempt. Of note, he was sacked only twice after being taken down six and four times respectively in Weeks 1 and 2, which almost certainly contributed to his stellar performance. Already a top flight fantasy option, Watson will look to keep things in Week 4 against the Panthers."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2577417.png",
        "name": "Dak Prescott",
        "depthchart": "Starter",
        "team": "Dallas Cowboys",
        "projected": 18.4,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#7F9695",
        "tmColorDark": "#041E42",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
        "headlineNews": "Accounts for three touchdowns",
        "report": "Prescott completed 19 of 32 pass attempts for 246 yards, two touchdowns, and one interception Sunday against the Dolphins. He also carried twice for seven yards and a touchdown during the 31-6 win.",
        "analysis": "Prescott started off a bit slowly, leading his team to just 10 points in the first half while throwing an ill-advised interception on a deep attempt. He turned it up in the second half, during which he scored a rushing touchdown in addition to firing a second scoring pass to Amari Cooper. Prescott's yardage numbers have come back to earth after his 405-yard eruption in the season opener, but he's still accounted for at least three touchdowns in each of his three appearances. He'll look to keep up his excellent start next Sunday on the road against the Saints."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3917792.png",
        "name": "Daniel Jones",
        "depthchart": "Starter",
        "team": "New York Giants",
        "projected": 18.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#A71930",
        "tmColorDark": "#0B2265",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
        "headlineNews": "Accounts for four touchdowns",
        "report": "Jones completed 23 of 36 pass attempts for 336 yards and two touchdowns Sunday against the Buccaneers. He also carried four times for 28 yards and a pair of touchdowns in the 32-31 win.",
        "analysis": "Making his first start, Jones completed 64 percent of his passes while averaging an impressive 9.3 yards per attempt. He threw touchdown passes to Evan Engram and Sterling Shepard in the third quarter while adding two rushing scores, including one from seven yards out to win the game in the final minutes. It was a terrific showing from the rookie, who will undoubtedly remain the starter next at home Sunday against Washington."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/12483.png",
        "name": "Matthew Stafford",
        "depthchart": "Starter",
        "team": "Detroit Lions",
        "projected": 18.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#0076B6",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
        "headlineNews": "Pulls out another victory",
        "report": "Stafford completed 18 of 32 passes for 201 yards and one touchdown during Sunday's 27-24 victory over the Eagles.",
        "analysis": "There were some missed opportunities that led to Stafford's pedestrian 56 percent completion rate, but the 31-year-old once again did enough to pull out the win. His performance - one that included zero taken sacks - proved vital since Detroit couldn't get its run game going against Philly's upper-echelon defensive front. It's too bad the success didn't translate to better numbers in the stat sheet, but Stafford's nonetheless averaging 277 passing yards with two passing touchdowns per game through three games and he'll get a chance to rebound in what could be a high-scoring affair when the Lions play host to the Chiefs in Week 4."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/15168.png",
        "name": "Case Keenum",
        "depthchart": "Starter",
        "team": "Washington Redskins",
        "projected": 17.9,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FFB612",
        "tmColorDark": "#773141",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
        "headlineNews": "Will remain starter",
        "report": "Coach Jay Gruden confirmed after Monday's 31-15 loss to the Bears that Keenum will remain the Redskins' starting quarterback for the Week 4 matchup with the Giants, Peter Hailey of NBC Sports Washington. \"Not really,\" Gruden said, when asked if he was considering a switch at quarterback. \"I can't be changing people every five minutes.\"",
        "analysis": "Though the Redskins took losses in their first two games, it was through little fault of Keenum, who completed 69.1 percent of his passes for 7.4 yards per attempt and a 5:0 TD:INT during that stretch. Things completely unraveled for Keenum on Monday, however, as he threw three picks and fumbled three times -- losing two of them -- as Washington dropped to 0-3. At least for now, Gruden will chalk up the ugly outing to a matchup versus a tough defensive unit, but Keenum may not be able to afford a rough showing versus a lackluster Giants defense. Rookie first-round pick Dwayne Haskins is next in line if Gruden decides to pull the plug on Keenum at any point."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/8439.png",
        "name": "Aaron Rodgers",
        "depthchart": "Starter",
        "team": "Green Bay Packers",
        "projected": 17.7,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FFB612",
        "tmColorDark": "#203731",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
        "headlineNews": "Starts hot, fades in win",
        "report": "Rodgers completed 17 of 29 passes for 235 yards and a touchdown during Sunday's 27-16 win over Denver.",
        "analysis": "Rodgers capped off the Packers' first drive with a patented 40-yard bomb to Marquez Valdes-Scantling\tafter Denver jumped offside and gave the Packers a free play. Though there was the occasional nifty pass, there wasn't much else going for Rodgers and the Packers. Part of that can be attributed to two Denver turnovers gifting the Packers short fields and 14 points, but fans might -- rightly -- remain concerned about Green Bay's early penchant for starting hot and cooling quickly. There won't be much time to correct course with a visit from the Eagles coming Thursday."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/14012.png",
        "name": "Andy Dalton",
        "depthchart": "Starter",
        "team": "Cincinnati Bengals",
        "projected": 17.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#ea7330",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
        "headlineNews": "Picked off late in close loss",
        "report": "Dalton completed 20 of 36 passes for 249 yards, one touchdown and two interceptions in Sunday's 21-17 loss to Buffalo. He added a one-yard touchdown rush.",
        "analysis": "Dalton failed to complete any of his five passes in the first quarter, and things didn't get much better through the air after that, but Dalton did manage to find the end zone with his legs from one yard out in the third quarter. He later fumbled on the 1-yard line but had the error wiped out by an offsides penalty. Dalton took advantage of the second chance with a one-yard touchdown pass to Joe Mixon on the very next play. The quarterback had a chance to be the hero late, but he was intercepted on Buffalo's 10-yard line in the final minute on a tipped ball."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2576980.png",
        "name": "Marcus Mariota",
        "depthchart": "Starter",
        "team": "Tennessee Titans",
        "projected": 17.0,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#4495D1",
        "tmColorDark": "#002A5C",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
        "headlineNews": "Won't lose job yet",
        "report": "Coach Mike Vrabel said Mariota isn't in danger of losing his starting job right now, Jim Wyatt of the Titans' official site reports.",
        "analysis": "The Titans are off to a 1-2 start, with Mariota taking 17 sacks and completing just 60.9 percent of his passes. Tennessee's offensive line may be part of the problem, but Mariota has shown a disturbing tendency to hold the ball for too long. His average time from snap to throw (2.97) is fourth-longest in the league, putting him on track for a second straight season leading the NFL in sack rate (15.6 percent this year, 11.3 percent in 2018). The Titans may consider a switch to Ryan Tannehill at quarterback if Mariota doesn't turn things around Week 4 in Atlanta."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3046779.png",
        "name": "Jared Goff",
        "depthchart": "Starter",
        "team": "Los Angeles Rams",
        "projected": 16.5,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#866D4B",
        "tmColorDark": "#024",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
        "headlineNews": "Finishes strong to lead team to win",
        "report": "Goff completed 24 of 38 pass attempts for 269 yards, two touchdowns and two interceptions in Sunday's 20-13 victory over the Browns.",
        "analysis": "Goff struggled to get things going against the Browns' tough front four, but he was able to find his rhythm in the second half with a pair of key touchdown drives. The 24-year-old had to improvise at times behind shoddy offensive line play, and that unit is going to have to improve drastically if we are going to see the elite passing numbers fantasy owners became accustomed to last season. Luckily for Goff's owners, the signal caller gets a favorable matchup this Sunday against a Buccaneers secondary that was just torched for 300-plus yards by rookie Daniel Jones."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3115293.png",
        "name": "Kyle Allen",
        "depthchart": "Starter",
        "team": "Carolina Panthers",
        "projected": 16.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#0085CA",
        "tmColorDark": "#101820",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
        "headlineNews": "Locked in for another start",
        "report": "Allen will get another start Week 4 against the Texans, Aaron Wilson of the Houston Chronicle reports.",
        "analysis": "Allen's success in Sunday's 38-20 win over Arizona may have contributed to the Panthers' decision to rule out Newton (foot) so early in the week. There was some talk of the 30-year-old quarterback returning to practice Wednesday, but he'll now be rested for at least one more game. Allen gets another matchup against a shaky pass defense, with the Texans allowing quarterbacks to complete 70.5 percent of their throws for 7.4 YPA and five touchdowns through three games."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3052587.png",
        "name": "Baker Mayfield",
        "depthchart": "Starter",
        "team": "Cleveland Browns",
        "projected": 16.0,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FF3C00",
        "tmColorDark": "#311D00",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
        "headlineNews": "Struggles in defeat",
        "report": "Mayfield completed 18 of 36 pass attempts for 195 yards, a touchdown and an interception in Sunday's 20-13 loss to the Rams.",
        "analysis": "Mayfield picked an inopportune time to have his worst game of the young season, as the Browns' defense gave its offense plenty of opportunities to pull off an upset. The second-year quarterback was under duress all game, and only found success on short throws, struggling to connect with his wideouts when dropping back deep in the pocket. ESPN's Jeff Trotter brought up the issue of Mayfield's struggles when holding onto the ball more than 2.5 seconds earlier this week, and Sunday's results reflected those early trends. The 24-year-old was averaging over 300 passing yards through his first two games, but his 3:5 TD:INT ratio will be harder to swallow when he posts yardage totals like Sunday's. Things won't get much easier for Mayfield in his next matchup against an athletic Ravens defensive unit."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2330.png",
        "name": "Tom Brady",
        "depthchart": "Starter",
        "team": "New England Patriots",
        "projected": 15.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#C60C30",
        "tmColorDark": "#002244",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
        "headlineNews": "Tops 300 yards in comfortable win",
        "report": "Brady completed 28 of 42 passes for 306 yards and two touchdowns in Sunday's 30-14 win over the Jets.",
        "analysis": "Brady threw a 25-yard touchdown to Phillip Dorsett in the first quarter and added a three-yard touchdown to Julian Edelman -- who later left the game with a chest injury -- in the second quarter. The quarterback was removed from the game with his team leading 30-7 in the fourth quarter but had to be reinserted after rookie Jarrett Stidham promptly threw a pick-six. A lack of weapons would become a bit of a concern if Edelman needs to miss additional time in the wake of Antonio Brown's release, but Brady still is at the helm of a dominant New England club and should continue to post impressive numbers after tossing multiple touchdowns in every game so far this season. He'll travel to Buffalo for another AFC East matchup Week 4."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3039707.png",
        "name": "Mitchell Trubisky",
        "depthchart": "Starter",
        "team": "Chicago Bears",
        "projected": 14.4,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#c36835",
        "tmColorDark": "#0B162A",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
        "headlineNews": "Throws three touchdowns in win",
        "report": "Trubisky completed 25 of 31 passes for 231 yards, three touchdowns and an interception in Monday night's 31-15 win over the Redskins.",
        "analysis": "Trubisky left some completions out there, but it was still a vastly improved performance after an uninspiring first two games of the season. He found Taylor Gabriel from three yards for his first touchdown of the campaign, then returned to Gabriel for two more scores, all during the second quarter. That included a superb 36-yard connection in the final minute before halftime, showcasing his ability to make plays on the run. Although a lousy fourth-quarter interception from the Redskins' six-yard line added a sour note toward the end, Trubisky can still be relatively pleased with his bounce-back performance in Week 3."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2578570.png",
        "name": "Jacoby Brissett",
        "depthchart": "Starter",
        "team": "Indianapolis Colts",
        "projected": 14.3,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#014683",
        "tmColorDark": "#002C5F",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
        "headlineNews": "Excels in Week 3 win",
        "report": "Brissett completed 28 of 37 passes for 310 yards with two touchdowns and no interceptions in the Colts' 27-24 win over the Falcons on Sunday. He also rushed three times for four yards.",
        "analysis": "Brissett came just four yards short of equaling his career high in passing yardage during a stellar showing, one in which he completed an outstanding 75.7 percent of his attempts. The fourth-year quarterback fired multiple passing touchdowns for the third time in as many games to open the season, and he averaged 8.4 yards per attempt while connecting with nine different pass catchers overall. Just as impressive was the fact Brissett was able to accomplish a chunk of his production without the services of T.Y. Hilton, who exited with a quadriceps injury. A brilliant start to his first season as the official successor to Andrew Luck already under his belt, Brissett will look to keep the magic going against the vulnerable Raiders defense Week 4."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/11252.png",
        "name": "Joe Flacco",
        "depthchart": "Starter",
        "team": "Denver Broncos",
        "projected": 13.5,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#e17757",
        "tmColorDark": "#024",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
        "headlineNews": "Turns it over twice",
        "report": "Flacco completed 20 of 29 passes for 213 yards and an interception during Sunday's 27-16 loss in Green Bay. He added five yards on two carries and lost a fumble.",
        "analysis": "It was enough relatively efficient though unspectacular day for Flacco, but a pair of turnovers stifled any chance the Broncos had of winning. After tying up the game in the second quarter and getting the ball back in the closing moments of the half, Flacco was stripped inside the 10-yard line, setting up an easy Packers score. Later, with Denver driving late in the third quarter, he air mailed an interception. Flacco has been better than Denver's ugly start has indicated, but he did the team no favors Sunday and now has to deal with a Jacksonville defense fresh off a beatdown of the Titans."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3886377.png",
        "name": "Josh Rosen",
        "depthchart": "Starter",
        "team": "Miami Dolphins",
        "projected": 13.1,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthQue": "Questionable",
        "tmColorLite": "#008E97",
        "tmColorDark": "#005778",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
        "headlineNews": "Has rough day versus Dallas",
        "report": "Rosen was being evaluated for a hand injury toward the end of Sunday's 31-6 loss to the Cowboys, according to Chris Perkins of The Athletic.",
        "analysis": "Rosen was checked out for an unrelated injury earlier in the game, and though he returned to the contest, he seemingly suffered another ailment in the latter stages. The second-year quarterback looked capable at times but faced a difficult matchup against a solid defensive unit and finished averaging just 5.1 yards per attempt. Rosen will be evaluated in the coming days, but he would carry minimal fantasy value in next Sunday's home matchup with the Chargers even if he is cleared of potential injuries."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/16728.png",
        "name": "Teddy Bridgewater",
        "depthchart": "Starter",
        "team": "New Orleans Saints",
        "projected": 12.7,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#D3BC8D",
        "tmColorDark": "#101820",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
        "headlineNews": "Clearly top option under center",
        "report": "Bridgewater completed 19 of 27 pass attempts for 177 yards and two touchdowns in Week 3 against the Seahawks. He also rushed the ball three times for 12 yards.",
        "analysis": "Bridgewater was helped by his defense and special teams, as the units put the first two touchdowns on the board for the Saints. However, he went on to orchestrate consecutive touchdown drives -- one to end the first half and the other to begin the second -- that put the team up big. Bridgewater didn't work down the field extensively by averaging only 6.6 yards per attempt, but did enough to post a respectable line while also maintaining the value of both Michael Thomas and Alvin Kamara. Perhaps most importantly, Bridgewater appears to be the clear starter and primary quarterback in the absence of Drew Brees (thumb) as Taysom Hill did not attempt a pass and rushed the ball just once for five yards. Bridgewater will look to keep things going in a primetime matchup Week 4 against the Cowboys."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/14880.png",
        "name": "Kirk Cousins",
        "depthchart": "Starter",
        "team": "Minnesota Vikings",
        "projected": 12.1,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FFC62F",
        "tmColorDark": "#251040",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
        "headlineNews": "Efficient in Week 3 win",
        "report": "Cousins completed 15 of 21 pass attempts for 174 yards and one touchdown, while adding four rushes for 16 yards during Sunday's 34-14 win against the Raiders.",
        "analysis": "Cousins may be capable of registering his first career postseason win this season as the starting quarterback for the Vikings, but his individual numbers thus far in 2019 are a distant cry from those he established as a member of the Redskins. With a star-studded defense in Minnesota, of course, he isn't being asked to do nearly as much to help his team win games. It is a small sample size to this point, but after a typically-prolific 2018 in his debut campaign for the Vikings, Cousins is on pace for a 2019 completion rate of 58.7, with a shade under 2,700 passing yards, and 16 touchdown passes to 11 interceptions. In three full seasons as the starter for Washington, he never threw for fewer than 4,000 yards or 25 touchdowns. He certainly does not project to have a huge fantasy outing in Week 4, taking on a Bears defense that has only surrendered two touchdown passes over its first two appearances of the year."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2969939.png",
        "name": "Jameis Winston",
        "depthchart": "Starter",
        "team": "Tampa Bay Buccaneers",
        "projected": 11.7,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#D50A0A",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
        "headlineNews": "Throws three TD passes",
        "report": "Winston completed 23 of 37 pass attempts for 380 yards, three touchdowns, and one interception during Sunday's 32-31 loss to the Giants.",
        "analysis": "Winston completed 62 percent of his pass attempts and averaged a healthy 10.3 yards per attempt thanks to some big gains through the air. He completed three touchdown passes to Mike Evans in the first half but his lone interception was equally important, coming while his team was marching toward the red zone in the fourth quarter. All in all, it was a much-improved performance from Winston, who averaged just 201 passing yards with three turnovers over the first two games. He'll face a tougher challenge on the road against the Rams next Sunday."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/2573079.png",
        "name": "Carson Wentz",
        "depthchart": "Starter",
        "team": "Philadelphia Eagles",
        "projected": 10.7,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#386168",
        "tmColorDark": "#004C54",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
        "headlineNews": "Pair of touchdowns in loss",
        "report": "Wentz completed 19 of 36 passes for 259 yards with two touchdowns and no interceptions in the Eagles' 27-24 loss to the Lions on Sunday. He also rushed four times for 33 yards.",
        "analysis": "Wentz ultimately put together a solid fantasy line, but he clearly missed wideouts Alshon Jeffery (calf) and DeSean Jackson (groin) against a feisty Lions defense. The fourth-year quarterback wasn't as sharp as usual overall, completing a season-low 52.8 percent of his throws. Wentz also took three sacks in the narrow loss and misfired deep to rookie J.J. Arcega-Whiteside on fourth down with 49 seconds remaining, an incompletion that sealed the defeat. Wentz and his offensive teammates won't have much time to correct mistakes, as they'll face the Packers in a Week 4 Thursday night tilt in which Wentz once again could be missing both of his aforementioned wideouts."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/4038524.png",
        "name": "Gardner Minshew",
        "depthchart": "Starter",
        "team": "Jacksonville Jaguars",
        "projected": 9.4,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#006778",
        "tmColorDark": "#101820",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
        "headlineNews": "Continues impressing in win",
        "report": "Minshew completed 20 of 30 passes for 204 yards with two touchdowns and no interceptions in the Jaguars' 20-7 win over the Titans on Thursday. He also rushed four times for 18 yards.",
        "analysis": "Someone clearly forgot to tell Minshew sixth-round quarterbacks don't just step right into a starting job Week 1 of their rookie campaign and hit the ground running. The Washington State product turned in another interception-free performance against a savvy veteran defensive unit, following an admirable effort in a road loss against the Texans just four days prior. Minshew set the tone early by capitalizing on a Titans' muffed punt with a seven-yard touchdown pass to James O'Shaughnessy, following it up later in the quarter by capping off a six-play, 62 yard march with a 22-yard scoring toss to DJ Chark. The first-year signal caller also helmed a pair of other possessions that ended in field goals and encouragingly avoided any fumbles after losing the handle on three occasions versus Houston. Jacksonville is just 1-2 with Thursday's win, but Minshew's play continues to give the team optimism he can hold down the fort during Nick Foles' (collarbone) absence. Minshew will look to continue his strong play when he faces a tough Broncos defense in Week 4 a week from Sunday."
    }
];

  $scope.teamtwo = [
  {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3051392.png",
        "name": "Ezekiel Elliott",
        "depthchart": "Starter",
        "team": "Dallas Cowboys",
        "projected": 19.2,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#7F9695",
        "tmColorDark": "#041E42",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
        "headlineNews": "This is a Headline",
        "report": "Jsdofs sdfsdfs sf sdfs sfds sdfsdfr.",
        "analysis": "Waso saeoi asd sadfoit sadoidf."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/3068267.png",
        "name": "Austin Ekeler",
        "depthchart": "Starter",
        "team": "Los Angeles Chargers",
        "projected": 18.1,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#0080C6",
        "tmColorDark": "#002A5E",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
        "headlineNews": "This is a Headline",
		"report": "Jsdofs sdfsdfs sf sdfs sfds sdfsdfr.",
        "analysis": "Waso saeoi asd sadfoit sadoidf."
	}
];


  $scope.teamthree = [
  {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/16737.png",
        "name": "Mike Evans",
        "depthchart": "Starter",
        "team": "Tampa Bay Buccaneers",
        "projected": 17.6,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#D50A0A",
        "tmColorDark": "#000000",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
        "headlineNews": "This is a Headline",
        "report": "Jsdofs sdfsdfs sf sdfs sfds sdfsdfr.",
        "analysis": "Waso saeoi asd sadfoit sadoidf."
    },
    {
        "imageUrl": "https://a.espncdn.com/i/headshots/nfl/players/full/16733.png",
        "name": "Odell Beckham Jr.",
        "depthchart": "Starter",
        "team": "Cleveland Browns",
        "projected": 14.9,
        "oponent": "Green Bay Packers",
        "lastweek": "Week Five: 32",
        "firstlast": "Week Four: 14",
        "secondlast": "Week Three: 18",
        "thirdlast": "Week Two: 19",
        "fourthlast": "Week One: 17",
        "hasStatus": "Status",
        "healthHea": "Healthy",
        "tmColorLite": "#FF3C00",
        "tmColorDark": "#311D00",
        "logoUrl": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
        "headlineNews": "This is a Headline",
		"report": "Jsdofs sdfsdfs sf sdfs sfds sdfsdfr.",
        "analysis": "Waso saeoi asd sadfoit sadoidf."
	}
];

  //adds the projected sum of each team 

  angular.forEach($scope.teamone, function(acc, index) {
    $scope.sumOne += acc.projected;
  });

  angular.forEach($scope.teamtwo, function(acc, index) {
    $scope.sumTwo += acc.projected;
  });

  //determines if you are projected to win or loose this week

  if ($scope.sumOne > $scope.sumTwo) {
    $('.compareMe').removeClass('lose')
      .addClass('win');
    $('.compareOpp').removeClass('win')
      .addClass('lose');
  } else if ($scope.sumOne < $scope.sumTwo) {
    $('.compareMe').removeClass('win')
      .addClass('lose');
    $('.compareOpp').removeClass('lose')
      .addClass('win');
  } else {
    $('.compareMe').removeClass('win')
      .removeClass('lose');
    $('.compareOpp').removeClass('win')
      .removeClass('lose');
  };

  //end of controller 
});

//other js
$(document).ready(function() {

  //open player modals
  $('.card').on('click', function() {
    $(this).next('.overlay')
      .addClass('showModal');
  });

  $('.close').on('click', function() {
    $('.overlay').removeClass('showModal');
  });

});